import React from 'react'

const AboutStnThree = () => {
    return (
        <div className="Abt-section-three">
            <p> <b> Currently,</b> I’m working primarily on the frontend side of web development while actively learning backend technologies to level up into a full-stack web developer. I enjoy building interfaces that don’t just look good but actually feel good to use, whether that means crafting clean modern layouts, experimenting with glassmorphism designs, or going full old-school with retro-style websites that give early-internet vibes. I’m the kind of developer who likes to understand how things work from the inside out, so while I’m polishing my frontend skills, I’m also diving into backend concepts to connect the dots and build complete, real-world applications. I’m a fast learner by nature, and once I get curious about something, I go all in—googling, breaking things, fixing them, and learning along the way. My long-term goal for the next 2–3 years is pretty clear: I want to become a solid full-stack web developer and shift to Japan to work there, experience the culture, and grow professionally in a global tech environment. I’m genuinely excited about building products that users actually enjoy using, not just projects that look good in a portfolio. I believe good design and good code should coexist, and I always try to balance creativity with performance and responsiveness. When I’m working, you’ll most likely find me with headphones on, listening to music and getting into that deep focus zone where time just disappears and the code starts flowing. Music keeps me in sync with my work and helps me stay creative, especially during long coding sessions. I’m still learning, still improving, and still pushing myself every day to be better than I was yesterday. I don’t claim to know everything—but I do know how to learn fast, adapt quickly, and stay consistent. I’m not afraid to experiment, fail, and rebuild from scratch if that’s what it takes to get things right. From smooth animations to functional layouts and evolving backend logic, I enjoy the entire process of turning ideas into working digital experiences. Right now, I’m focused on growth, discipline, and building skills that actually matter in the real world. Step by step, project by project, I’m working toward becoming a full-stack developer who can confidently build, scale, and maintain modern web applications—and eventually take that journey all the way to Japan 🇯🇵🚀.</p>
        </div>
    )
}

export default AboutStnThree